#!/bin/sh

set -e

mkdir ~/.vim && cd ~/.vim

# Create a local.vim for machine-specific customization
grep -sq 'VimrcLocal' after/plugin/local.vim || {
	mkdir -p after/plugin
	printf 'VimrcLocal " %s\n' "$(id -un)@$(uname -n)" \
		>> after/plugin/local.vim
}

# Install vim-plug...
curl -sSfL -o autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
